# Generated by Django 3.0.8 on 2021-05-10 12:57

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='audiobooks/')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='podcasts/')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('uploaded_time', models.DateTimeField(auto_now=True)),
                ('participants', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1009, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='songs/')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
