# Generated by Django 3.0.8 on 2021-05-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='file',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file',
        ),
    ]
