# Generated by Django 3.0.8 on 2021-05-10 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20210510_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
